const url='https://integrate.api.nvidia.com/v1/chat/completions';
const tasks={
poem:'Schreibe ein persönliches deutsches Gedicht. Es soll natürlich, herzlich und nicht kitschig wirken.',
recipe:'Erstelle aus den genannten Zutaten drei passende gesunde Rezeptideen. Gib danach für die beste Idee Zutatenmengen und einfache nummerierte Schritte an.',
english:'Sei eine freundliche Englischlehrerin für eine deutschsprachige erwachsene Anfängerin. Antworte mit einem kurzen englischen Satz, deutscher Übersetzung und nur einer einfachen Übungsfrage.',
card:'Erstelle eine hochwertige, genaue Bildbeschreibung für eine personalisierte Grußkarte. Gib zuerst den Text für die Karte und danach einen bildgeneratorfertigen Prompt ohne Erklärungen.',
music:'Schlage passend zur Stimmung drei Musik- oder Tanzideen vor und erkläre kurz, warum sie passen.'};
const out=(s,b)=>({statusCode:s,headers:{'content-type':'application/json','cache-control':'no-store'},body:JSON.stringify(b)});
export async function handler(e){if(e.httpMethod!=='POST')return out(405,{error:'Nur POST'});if(!process.env.NVIDIA_API_KEY)return out(503,{error:'Momo braucht noch den NVIDIA_API_KEY in Netlify.'});let b;try{b=JSON.parse(e.body||'{}')}catch{return out(400,{error:'Ungültige Anfrage'})}const task=tasks[b.task]||tasks.poem,input=String(b.input||'').slice(0,5000);if(!input.trim())return out(400,{error:'Bitte fülle mindestens ein Feld aus.'});try{const r=await fetch(url,{method:'POST',headers:{authorization:`Bearer ${process.env.NVIDIA_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.NVIDIA_MODEL||'nvidia/nemotron-3-nano-30b-a3b',messages:[{role:'system',content:`Du bist Momo, eine warme, geduldige Kreativbegleiterin. Verwende klares Deutsch, keine Fachbegriffe und keine Prompt-Sprache. ${task}`},{role:'user',content:input}],temperature:.7,max_tokens:900})});const d=await r.json();if(!r.ok)throw Error(d.message||'NVIDIA antwortet nicht');return out(200,{text:d.choices?.[0]?.message?.content||'Momo hat gerade keine Idee gefunden.'})}catch(x){return out(502,{error:x.message})}}
